version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - EMAIL=a.nuradil.m@gmail.com
      - H2_USERNAME=admin
      - H2_PASSWORD=admin
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - test-task-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  test-task-network:
    driver: bridge

volumes:
  redis-data:
