spring:
  datasource:
    url: jdbc:h2:file:./test_task
    username: ${H2_USERNAME:admin}
    password: ${H2_PASSWORD:admin}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: testmail6743@gmail.com
    password: xzxz aswk gjwc ngvi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

custom-user-details:
  username: ${USER_NAME:admin}
  password: ${PASSWORD:admin}
  email: ${EMAIL}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
